### ISSUE TITLE
URLs for Philips TV sets

### ISSUE THREAD

**Issue by Waringham** [Perflyst/PiHoleBlocklist#1]
I have monitored my Philips TV set with Pi-Hole for a couple of weeks and found several requests to following URLs:

a.root-servers.net
deviceportal.nettvservices.com
epg.corio.com
legacyportal.nettvservices.com
nettv.corio.com
www.ecdinterface.philips.com

You may want to add the URLs to your list.

**Comment by Perflyst** [comment]
Sorry for this late answer. I will add all of them, except a.root-servers.net. This should be blocked because a request from a TV to a DNS root server should not be, but this has nothing exlplicitly to do with a TV.

**Comment by ngaggi** [comment]
please remove www.ecdinterface.philips.com from list, because it's essential for Philips Hue and Amazon Alexa / Echo integration.
Putting this FQDN on Pi-hole whitelist brings my Hue to work again.

**Comment by Waringham** [comment]
This is a blocklist. Data with unknown payload will be sent to this URL from your Philips devices and/or internal network devices. Also, this URL is not TLS secured. So  a man-in-the-middle attack is possible. If you do not want to block this URL, you can unsubscribe from this blocklist or add the URL to your private whitelist.
