### ISSUE TITLE
time.samsungcloudsolution.com causes certain apps to stop working

### ISSUE THREAD

**Issue by agyild** [Perflyst/PiHoleBlocklist#10]
The domain `time.samsungcloudsolution.com` when blocked, prevents services such as Plex and YouTube from starting on Samsung KU7000 on a reboot. When whitelisted however they work just fine.

**Comment by Timi7007** [comment]
According to various Reddit and Pi-Hole forum posts Amazon Video is also affected. After adding an exception to the whitelist it works. Also refer to the comments on https://gist.github.com/Perflyst/315f86393712a0c2107ee8eb58c6acee/

**Comment by Perflyst** [comment]
Than please whitelist it. There goes telemetry out and I don't want this. I even don't use any corporate services like amazon video.

**Comment by Timi7007** [comment]
Would it make sense to comment it out with a note? Netflix is also allowed (`#mhc-ajax-eu.myhomescreen.tv // if blocked, unable to use smarttv apps e.g. Netflix, AmazonVideo as TV calls home for connection check`) so the continuity would make sense.
