### ISSUE TITLE
Adding the raw file doesn't download the adlist correctly

### ISSUE THREAD

**Issue by plsnotracking** [Perflyst/PiHoleBlocklist#102]
Adding the raw github link gives me the following error:
```
Health status of this list: | List was not downloaded so far
-- | --
This list was added to Pi-hole | a few seconds ago (2021-06-23 20:29:44)
Database entry was last modified | a few seconds ago (2021-06-23 20:29:44)
The list contents were last updated | N/A
Number of valid domains on this list: | N/A
Number of invalid domains on this list: | N/A
```
![Screenshot](https://user-images.githubusercontent.com/54467867/123198347-cb244480-d461-11eb-8917-d42b18daec1e.png)

Please let me know what I'm doing incorrectly.

**Comment by Perflyst** [comment]
Try this one instead https://perflyst.github.io/PiHoleBlocklist/SmartTV.txt
