### ISSUE TITLE
Samsung TV Regex List Issues

### ISSUE THREAD

**Issue by EthanG45** [Perflyst/PiHoleBlocklist#103]
Hello,

I was recently setting up the regex list on my Pi-hole and noticed some issue on my RU8000 Samsung TV.

The following line prevents connecting to the internet.

https://github.com/Perflyst/PiHoleBlocklist/blob/d3c45db0030dce3e835d80e7cf85372a499e0b57/regex.list#L16

The following two lines prevent checking for updates. These seem kind of tricky because from what I can tell unblocking these seems to allow the “free” content ad section to populate with sponsored content. Perhaps just a comment noting this happens and to disable them when checking for updates would work.
https://github.com/Perflyst/PiHoleBlocklist/blob/d3c45db0030dce3e835d80e7cf85372a499e0b57/regex.list#L15

https://github.com/Perflyst/PiHoleBlocklist/blob/d3c45db0030dce3e835d80e7cf85372a499e0b57/regex.list#L19

I wanted to hear if others see this on their Samsungs. Thanks!

**Comment by DandelionSprout** [comment]
My pa has a Samsung TV with the same production year and OS, but with a different series number. I'll see if I can look into it today or tomorrow at latest.

**Comment by DandelionSprout** [comment]
Sorry that I forgot this for a week ago. I was originally hoping for #104 to get merged, but now I see that all 3 of those domains are already removed or non-RegEx-ed from the list's AdGuard Home version, most likely for good reasons.

Thus I vote in favour of removing those three entries from the Pi-hole RegEx list.
