### ISSUE TITLE
RegEx is blocking DNS queries without TLD, i.e. local queries

### ISSUE THREAD

**Issue by asche77** [Perflyst/PiHoleBlocklist#108]
At least on Adguard Home, the following RegEx prevents clients from looking up local hosts by using only their hostname:
```
! For TVs that try to connect to several garbled letter combinations
/^[a-z]{7,15}$/
```

This prevents e.g. lookups of "NAS" or "printer" whereas "NAS.mydomain.TLD" or "printer.local" would work.

Could that RegEx be removed or limited (e.g. to only catch GarbledSomethingDOTanydomainDOTanyTLD ?) My RegEx skills are pretty basic but something like adding "\\." at the end perhaps?

**Comment by DandelionSprout** [comment]
It was complete news to me, after 2½ years of owning a Raspberry Pi with AdGuard Home, that LAN units could use hostnames that weren't "localhost". I'll address this later tonight (unless I forget about this repo once again. 😅).
