### ISSUE TITLE
Invalid domains

### ISSUE THREAD

**Issue by iteqla** [Perflyst/PiHoleBlocklist#109]
When adding the list to Gravity, the following error message appears

[i] Target: https://perflyst.github.io/PiHoleBlocklist/SmartTV-AGH.txt
  [✓] Status: Retrieval successful
  [i] Analyzed 209 domains, 204 domains invalid!
      Sample of invalid domains:
      - ||smartclip.com^
      - ||smartclip.net^
      - ||myhomescreen.tv^
      - @@||mhc-ajax-eu.myhomescreen.tv^
      - @@||mhc-ajax-eu-s2.myhomescreen.tv^

**Comment by DandelionSprout** [comment]
Do you have a link to the Gravity tool (as I've honestly never heard of it before)? It is very likely that you should use the https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt version of the list instead.

**Comment by DandelionSprout** [comment]
I don't think you got my point. If I am correct on my guess, Gravity (whatever that is) *does not support AGH lists*, only raw domains lists.

**Comment by iteqla** [comment]
What do you mean with "_Gravity (whatever that is)_"?
Your repository is called PiHoleBlocklists, so I am assuming the list are meant for Pihole. If they are meant for something else, I guess that closes the issue. 
The Gravity is the list of the domains that have been processed by Pihole's gravity (pihole -g) command.

PiHole cannot validate the domain in your list.
See screenshots for further details too.

![gravity 01](https://user-images.githubusercontent.com/38462266/146398025-591d1840-69b7-4d27-a85d-5bb1ac7fe612.jpg)
![gravity 02](https://user-images.githubusercontent.com/38462266/146398032-31448a1b-57c8-459f-95ed-d38582b6317e.jpg)
![gravity 03](https://user-images.githubusercontent.com/38462266/146398895-9be7fb10-16c9-456d-a1b9-8b121f195ce0.jpg)
.

**Comment by DandelionSprout** [comment]
https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt is the Pi-hole version, the original list version, and the version used by Perflyst himself; whereas https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV-AGH.txt was a somewhat late addition (Late 2019).

As awesome as it'd be to simply change repo and file names on GitHub, it's far from easy to do for adblock lists (except for Adblock Plus), since those who already use the lists would need to manually replace the old links with the new links. 😅

**Comment by iteqla** [comment]
Thanks for the explanation.
Perhaps, if repository and files name are impossible to change, then the resolution of the problem could be adding a line to the existing description in the file itself. Something like:

! Title: Smart-TV Blocklist for AdGuard Home (by Dandelion Sprout's)
! Version: 10July2021v1
! Description: This is a blocklist to block smart-TVs sending metadata back home, sometimes with the added benefit of blocking interface ads for apps and movie services.
! Please help to collect domains!
! It could occur that the TV fails to receive new updates, or that other apps or services no longer work. Please report such an incident.
`!======== This list is not compatible with Pi-Hole ========`

**Comment by DandelionSprout** [comment]
#119 aims to add such a line, but it depends on Perflyst going online again to merge it. 😅
