### ISSUE TITLE
Fantasy Football Players are blocked

### ISSUE THREAD

**Issue by JamesTeague** [Perflyst/PiHoleBlocklist#110]
`api.nfl.com` seems a little broad. If you do actually play fantasy football and use the app from the NFL, you will not be able to load the app. I've whitelisted, but it seems that if you are making these requests from your network, chances are you are playing fantasy football or trying to watch content on the NFL website or affiliate application.

**Comment by Perflyst** [comment]
Fixed with https://github.com/Perflyst/PiHoleBlocklist/pull/111
