### ISSUE TITLE
Auto Date & Time breaks on LG Smart TV after cold boot / restart

### ISSUE THREAD

**Issue by SensehacK** [Perflyst/PiHoleBlocklist#117]
If you unplug the switch or turn off tv automatically.
The LG TV when it boots again makes a connection request to 
`us.lgtvsdp.com` address where it gets its latest date and time or else resets to December 31st 2019.

If it doesn't has the latest time it would have issues with server certificates - 
Apps: 
- Plex says network unreachable
- HBO Max (shows the proper error of the date & time being set behind the current time range server accepts the certificates to generate & make the appropriate handshake)
- Youtube just reloads its boot animation.

I observed that LG TV makes connection request at the first boot 2 times with 30 - 45 secs interval.

By whitelisting this address `us.lgtvsdp.com` and cold booting / switching off the tv completely - unplug the power. Makes it loose the temporary date and time so it makes the request to that connection for latest date and time.
<img width="1454" alt="Screen Shot 2021-11-30 at 5 16 04 PM" src="https://user-images.githubusercontent.com/8469205/144149202-a377cac2-ee6a-43e7-a37c-05b3b96cb769.png">

**Comment by DandelionSprout** [comment]
I seem to have problems reproducing this on a 2017-model LG 43UH603V. How long does the power have to be unplugged in order for the date to be reset?

**Comment by DandelionSprout** [comment]
Ignore my above comment; turns out `us.lgtvsdp.com` was blocked in the Pi-Hole list version, but not in the AdGuard Home list version that I use. I'll address this later tonight.
