### ISSUE TITLE
android.clients.google.com blocks android OS from reaching google play store.

### ISSUE THREAD

**Issue by jayschieber** [Perflyst/PiHoleBlocklist#12]
android.clients.google.com blocks android OS from reaching google play store., which seems too aggresive.

**Comment by Perflyst** [comment]
With which android version do you have issues?
There are no with android 7.1.2 and lower. I tested 7.1.2, 7.0 and 6.0

**Comment by jayschieber** [comment]
8.0.0

**Comment by Timi7007** [comment]
I can confirm this problem with Android 9 Pie (Nov 5, 2018) on a Google Pixel 2.

**Comment by Perflyst** [comment]
Seems like only newer android version need this domain. Can someone list all domains which are needed to reach google play via phone on newer android versions, please?

**Comment by Timi7007** [comment]
These are all requests my phone makes while in the Play Store:
~~~
lh3.googleusercontent.com (unsure)
googleads.g.doubleclick.net (Pi-holed)
ssl.google-analytics.com (Pi-holed)
android.clients.google.com (required)
books.google.com (unsure)
lh5.ggpht.com (unsure)
lh3.ggpht.com (unsure)
lh4.ggpht.com (unsure)
lh4.googleusercontent.com (unsure)
play.googleapis.com (unsure)
lh6.googleusercontent.com (unsure)
lh5.googleusercontent.com (unsure)
www.googleadservices.com (Pi-holed)
epdg.epc.mnc002.mcc262.pub.3gppnetwork.org (probably unrelated for the store, but required when GSM signal is low to make calls stronger using WiFi)
r5---sn-i5heen7s.gvt1.com (Google Content, required for Chrome, browser extensions and app updates)
cloudconfig.googleapis.com (unsure)
lh6.ggpht.com (unsure)
www.google.com (probably important)
support.google.com (required for the help page)
www.gstatic.com (probably important)
fonts.googleapis.com (probably important)
ssl.gstatic.com (probably important)
api.leanplum.com (Pi-holed, probably unrelated / another app)
app.adjust.com (Pi-holed, probably unrelated / another app)
~~~
The "(Pi-holed)"-ones can be killed, the "(required)"-ones definitively can't. The "(probably important)"-ones I wouldn't dare to block. The "(unsure)"-ones are probably required in some way, I will test blocking them later (thanks, cache).
