### ISSUE TITLE
LG TV - Region based domains

### ISSUE THREAD

**Issue by xMateMCPE** [Perflyst/PiHoleBlocklist#15]
The LG TV uses different subdomains for each region.
Example for hungary: us.lgtvsdp.com -> hu.lgtvsdp.com, us.ad.lgsmartad.com -> hu.ad.lgsmartad.com, etc
The hosts file should be replaced with a wildcard(or what Pi-Hole uses) for every "us" in the LG domains.

**Comment by Perflyst** [comment]
I am not sure if blocklists support regex, as far as I know you can set regex rules only through a second file or via webinterface. I will look at this.

**Comment by Perflyst** [comment]
This is not possible yet (tested on develop branch), I will keep it open anyways maybe we can do this with next versions.
