### ISSUE TITLE
My Samsung tv Q6FN model is not connecting to internet

### ISSUE THREAD

**Issue by dakotate** [Perflyst/PiHoleBlocklist#19]
I have a Samsung tv Q6FN model and I am unable to connect it to internet, any idea of what is preveting the internet connection? 

Please note that the tv has never been connected to internet, so I still have to accept the terms and conditions for the smart connectivity but the missing of connectivity is preventing even the terms and conditions page to load.

Hope you can help. Thank u!

**Comment by Perflyst** [comment]
I do not have this TV. Can you please take a look into the pihole query logs?

**Comment by dakotate** [comment]
I do not have a raspberry sorry

**Comment by Perflyst** [comment]
Maybe you disable all your blocking for the initial connection and enable it later again? Should work and this ugly workaround is sometimes needed.

**Comment by Perflyst** [comment]
Please provide more information, than we can re-open
