### ISSUE TITLE
collect-eu-fy2017.myhomescreen.tv

### ISSUE THREAD

**Issue by EalingHorizon** [Perflyst/PiHoleBlocklist#20]
My newish Panny TV connects to:
collect-eu-fy2018.myhomescreen.tv
usage-eu-fy2018.myhomescreen.tv

Not sure if 2018 unilaterally replaces 20[<18]  or if the url is related to the year of manufacture of the device.

I also have a 2016 Panny PVR which connects to a completely different bunch of URLs. Can analyse and document if required, but a shed load of work.

**Comment by Perflyst** [comment]
I dont know exactly what 20XX urls they connect to. At least they dont change with software updates.

If you can, please collect everything you can get!

**Comment by Perflyst** [comment]
I have added your domains and a few more with same format with 3e945d11bbb7f78c5cc2777b34d89d8519ab969a

**Comment by EalingHorizon** [comment]
Looks good; thanks.
I suspect cert-test.sandbox.google.com (a url to test https certificates) could be redundant in this context.
0077777700140002.myhomescreen.tv is more interesting. I think you could/should delete that too because I think the number refers to one individual TV/device.
I am seeing [different-very-long-number].myhomescreen.tv being accessed.

**Comment by Perflyst** [comment]
Is there any productive content served from *.myhomescreen.tv? Otherwise this should be added as wildcard

**Comment by EalingHorizon** [comment]
Tested by adding that to the wildcard blacklist.
Freeview Play still works. iPlayer still works.

**Comment by Perflyst** [comment]
PiHole does not support wildcard lists yet. Anyways for the moment as this is the second issue I will add a wildcard.txt
