### ISSUE TITLE
Potential additions to Sony blocklist

### ISSUE THREAD

**Issue by NCLI** [Perflyst/PiHoleBlocklist#24]
facemap.foldlife.net
static-cdn.jtvnw.net
bdcore-apr-lb.bda.ndmdhs.com

I've tested with these blocked for a while, with no ill-effects.

**Comment by mervburger** [comment]
>static-cdn.jtvnw.net

This is part of the CDN for Twitch.tv, and will interfere with legitimate traffic. This will prevent most static elements from loading, such as emotes in chat, and channel thumbnail images.
