### ISSUE TITLE
hbbtv - zdf, prosieben

### ISSUE THREAD

**Issue by HellboyPI** [Perflyst/PiHoleBlocklist#29]
hbbtv.zdf.de, hbbtv.redbutton.de, hbbtv.prosieben.de - blocks ZDF & ProSieben tv apps from starting. 
Could someone test what is the situation with other apps in the HBBTV group?

Also, you have duplicate entries in the HBBTV group.

**Comment by Perflyst** [comment]
Closed via e0d7175787642db9854e950e0ef05a74f3afcfc1
