### ISSUE TITLE
Philips TV - deviceportal.nettvservices.com, epg.corio.com, ad.nettvservices.com

### ISSUE THREAD

**Issue by HellboyPI** [Perflyst/PiHoleBlocklist#31]
deviceportal.nettvservices.com
epg.corio.com

When these 2 domains are blocked, the apps (YT, Vimeo,...) on the Philips SmartTV won't start or won't work as expected. They should be whitelisted (removed from the blocklist).

ad.nettvservices.com - this domain (advertising) should be put on the blocklist

**Comment by Perflyst** [comment]
Thanks, fixed
