### ISSUE TITLE
Samsung UN43NU6900 Issue

### ISSUE THREAD

**Issue by Z3ROGRAV1TYx** [Perflyst/PiHoleBlocklist#32]
I'm having issues with the SmartTV Blocklist on Samsung UN43NU6900 when installing apps.
Any ideas which I have to whitelist? I tried the few commented in the txt file but didn't seem to work.

**Comment by Perflyst** [comment]
Check your pihole logs to see what exactly is requested if you try to install an app

**Comment by Perflyst** [comment]
If you find the issue please report and we can re-open
