### ISSUE TITLE
[INFO] Additional domains

### ISSUE THREAD

**Issue by fred-cardoso** [Perflyst/PiHoleBlocklist#33]
Hello!

I detected two additional domains under Samsung Smart TV:

osb-ussvc.samsungqbe.com
otn.samsungcloudcdn.com

Also, the TV, for some reason queries the following domains:
www.google-analytics.com
uts-preview.itunes.apple.com
bag.itunes.apple.com
is1-ssl.mzstatic.com
is2-ssl.mzstatic.com
is3-ssl.mzstatic.com
is5-ssl.mzstatic.com

I blocked them all on my side.

**Comment by Perflyst** [comment]
I added the two domains with 58c5e2c5a2a4b5360f2413bdc734cbdb51e30542
the mzstatic.com domains are needed for the apple appstore

**Comment by hmhrex** [comment]
The `osb-ussvc.samsungqbe.com` domain is actually blocking a bunch of stuff on my Samsung TV.

**Comment by fred-cardoso** [comment]
> The `osb-ussvc.samsungqbe.com` domain is actually blocking a bunch of stuff on my Samsung TV.
> 
> I've had to whitelist this in Pihole in order to get Universal Search and some other parts of the TV to work.

Write here, still using, no problems whatsoever. I will keep you guys updated.

**Comment by Perflyst** [comment]
@hmrex sorry, I missed this reply. What does not work for example?
