### ISSUE TITLE
Should we blacklist the whole domain nflxso.net?

### ISSUE THREAD

**Issue by samirwrahman** [Perflyst/PiHoleBlocklist#34]
Hi, I am new to pihole and just installed it along with a new smart tv today. I noticed two different dns queries to nflxso.net that weren't covered in these rules:  cfovj3dlskjrvopwjruhs-usw2.r.nflxso.net and occ-0-1479-1480.1.nflxso.net. Should we just blacklist this entire domain? I did this and saw my netflix seemed to work fine.

**Comment by Perflyst** [comment]
https://news.ycombinator.com/item?id=19238519
nflxso.net is not a tracker. It is a domain used by Netflix to refer to "small" non-video downloadables (things like the images you see when browsing titles on the web or in the app).

Can you check this statement, please?

**Comment by samirwrahman** [comment]
Sorry for the slow response. If that's the case, why include occ-0-399-783.1.nflxso.net at all?

**Comment by Perflyst** [comment]
I have removed it.
