### ISSUE TITLE
SmartTV list; www.ecdinterface.philips.com causes Philips Hue Bridge to blink internet light 

### ISSUE THREAD

**Issue by TorchedPoseidon** [Perflyst/PiHoleBlocklist#35]
SmartTV list; www.ecdinterface.philips.com causes Philips Hue Bridge to blink internet light. I haven't been able to test reliably if it actually cuts off internet and messes with external control but it's clear that Philips Hue is using this domain.

**Comment by Perflyst** [comment]
https://news.ycombinator.com/item?id=19238519
 nflxso.net is not a tracker. It is a domain used by Netflix to refer to "small" non-video downloadables (things like the images you see when browsing titles on the web or in the app). 

Can you check this statement, please?

**Comment by TorchedPoseidon** [comment]
> https://news.ycombinator.com/item?id=19238519
> nflxso.net is not a tracker. It is a domain used by Netflix to refer to "small" non-video downloadables (things like the images you see when browsing titles on the web or in the app).
> 
> Can you check this statement, please?

Did you mean to reply to [this issue](https://github.com/Perflyst/PiHoleBlocklist/issues/34)?  
Either way, based on some light use of Netflix with `occ-0-399-783.1.nflxso.net` blacklisted I can't detect broken functionality, but that's no guarantee, haven't extensively tested it.

**Comment by Perflyst** [comment]
Yes, sorry.
