### ISSUE TITLE
Samsung TV

### ISSUE THREAD

**Issue by Redback813** [Perflyst/PiHoleBlocklist#39]
I have a list of blocks for the Samsumg Model I have so this might help others.

# Samsung list DNSMASQ
#server=/.worldtimeserver.com/
#server=/auth.samsungosp.com // if blocked, samsung accounts will fail to authenticate
#server=/cdn.samsungcloudsolution.com # System update check on Samsung UE40F5500
#server=/d1oxlq5h9kq8q5.cloudfront.net/ # Cripples the Samsung Apps GUI on Samsung UA40F6300
#server=/deliver.oztam.com.au # OzTAM is an Australian audience measurement research.
#server=/infolink.pavv.co.kr/ # Needed for appstore and login on Samsung UE40F5500, WHOIS & Domain Info UA40F6300
#server=/ns11.whois.co.kr/ Cripples Network Connection on Samsung UA40F6300
#server=/pavv.co.kr/ # Needed for appstore and login on Samsung UE40F5500, WHOIS & Domain Info for UA40F6300
#server=/samsungosp.com/
#server=/time.samsungcloudsolution.com/ #if blocked, services like Plex, YouTube and PrimeVideo will not work.
#server=/www.samsungotn.net/ # system update check on Samsung
server=/.bigdata.ssp.samsung.com/
server=/abtauthprd.samsungcloudsolution.com/
server=/acr0.samsungcloudsolution.com/
server=/ad.samsungadhub.com/
server=/ads.aimitv.com/
server=/ads.samsungads.com/
server=/amauthprd.samsungcloudsolution.com/
server=/api-hub.samsungyosemite.com/
server=/apu.samsungelectronics.com/
server=/az43064.vo.msecnd.net/
server=/bpu.samsungelectronics.com/
server=/cdn.samsungcloudsolution.net/
server=/config.samsungads.com/
server=/configprd.samsungcloudsolution.net/
server=/Coordinator-Production-28516768.us-east-1.elb.amazonaws.com/
server=/cpu.samsungelectronics.com/
server=/d179kwmlpc4o47.cloudfront.net/
server=/d1jwpcr0q4pcq0.cloudfront.net/
server=/d2tnx644ijgq6i.cloudfront.net/
server=/d37ju0xanoz6gh.cloudfront.net/ #Ads
server=/d3mjsomixevyw7.cloudfront.net/
server=/dev-multiscreen.samsung.com/
server=/device-metrics-us.amazon.com/
server=/dly2224qfzjce.cloudfront.net/
server=/dpu.samsungelectronics.com/
server=/empdownprd.samsungcloudsolution.com/
server=/fkp.samsungcloudsolution.com/
server=/fkp.samsungcloudsolution.net/
server=/gallery.tv.widgets.yahoo.com/
server=/game.internetat.tv/
server=/gamespromotion.samsungcloudsolution.com/
server=/gld.samsungosp.com/
server=/gpm.samsungqbe.com/
server=/i-stream.pl/
server=/kpu.samsungelectronics.com/
server=/lcprd1.samsungcloudsolution.net/
server=/log-1.samsungacr.com/
server=/log-2.samsungacr.com/
server=/log-3.samsungacr.com/
server=/log-ingestion-eu.samsungacr.com/
server=/log-ingestion.samsungacr.com/
server=/log.internetat.tv/
server=/multiscreen.samsung.com/
server=/musicid.samsungcloudsolution.com/
server=/notice.samsungcloudsolution.com/
server=/noticecdn.samsungcloudsolution.com/
server=/noticefile.samsungcloudsolution.com/
server=/noticeprd.cloudapp.net/
server=/noticeprd.trafficmanager.net/
server=/oempprd.samsungcloudsolution.com/
server=/oempprd.samsungcloudsolution.net/
server=/openapi.samsung.com/
server=/osb-apps.samsungqbe.com/
server=/osb-eusvc.samsungqbe.com/
server=/osb-krsvc.samsungqbe.com/
server=/osb-ussvc.samsungqbe.com/
server=/osb.samsungqbe.com/
server=/otn.samsungcloudcdn.com/
server=/otnprd10.samsungcloudsolution.net/
server=/otnprd11.samsungcloudsolution.net/
server=/otnprd8.samsungcloudsolution.net/
server=/otnprd9.samsungcloudsolution.net/
server=/oztam.com.au/ # OzTAM is an Australian audience measurement research firm that collects and markets television ratings data.
server=/pipeaota.com/
server=/premium-videos.telly.com/
server=/prov.samsungcloudsolution.com/
server=/rd.samsungadhub.com/
server=/rwww.samsungotn.net/
server=/samsungacr.com/
server=/samsungadhub.com/
server=/samsungads.com/
server=/samsungelectronics.com/
server=/samsungqbe.com/
server=/samsungresources.visionobjects.com/
server=/samsungrm.net/
server=/sas.samsungcloudsolution.com/
server=/saturn.tiser.com.au/
server=/sca.samsung.com/
server=/sso.internetat.tv/
server=/svwindow.samsungcloudsolution.com/
server=/syncplusconfig.s3.amazonaws.com/
server=/targeted-config-test.samsungacr.com/
server=/test.samsungrm.net/
server=/time.trafficmanager.net/
server=/upu.samsungelectronics.com/
server=/us-api.samsungyosemite.com/
server=/vd.contents.prod.eu.s3.amazonaws.com/
server=/vd.emp.prd.s3.amazonaws.com/
server=/vdterms.samsungcloudsolution.com/
server=/www.samsungrm.net/
server=/xpu.samsungelectronics.com/
server=/ypu.samsungelectronics.com/
server=/zpu.samsungelectronics.com/

**Comment by Perflyst** [comment]
Thanks, I will go through it when I have some more time
