### ISSUE TITLE
Consider blocking additional domains for Samsung TV’s

### ISSUE THREAD

**Issue by DavidAnson** [Perflyst/PiHoleBlocklist#41]
https://www.reddit.com/r/pihole/comments/dedpfe/samsung_smart_tv_sending_thousands_of_requests_in/

The above thread mentions a few, including `giraffic` which I see in logs along with `samsungcloudcdn` The letter is already present in this list and is queried every 2 minutes, non-stop. The former does not seem to be and is queried about every 10 minutes.

Thanks for creating this!

**Comment by Perflyst** [comment]
Thanks, for reference
```
(^|\.)giraffic\.com$
(^|\.)internetat\.tv$
(^|\.)pavv\.co\.kr$
(^|\.)samsungcloudcdn\.com$
(^|\.)samsungcloudsolution\.com$
(^|\.)samsungcloudsolution\.net$
(^|\.)samsungelectronics\.com$
(^|\.)samsungotn\.net$
(^|\.)samsungrm\.net$
```
should be added

**Comment by Perflyst** [comment]
Closed via https://github.com/Perflyst/PiHoleBlocklist/pull/51
