### ISSUE TITLE
Unblocking some Samsung TV URLs to re-enable functionality & blocking other tracking URLs

### ISSUE THREAD

**Issue by redanish** [Perflyst/PiHoleBlocklist#49]
osb-ussvc.samsungqbe.com
^ unblocking this is the bare minimum required to make the "TV Plus" app work. Blocking any samsungqbe.com may break at least some "TV Plus" app ability. However, I have been able to block most samsungqbe.com URLs and just unblock osb-ussvc.samsungqbe.com to make "TV Plus" work. **This should be unblocked.**

otn.samsungcloudcdn.com
otnprd10.samsungcloudsolution.net
otnprd11.samsungcloudsolution.net
otnprd9.samsungcloudsolution.net
www.samsungotn.net

^ Blocking any of these URLs will cause the TV's ability to update its software OTA.
Blocking them causes CURL errors in the software update section of the settings app. T**his should be unblocked.**

lcprd1.samsungcloudsolution.net
^ This URL causes the TV to ping constantly, I don't think this is a beaconing URL and can be removed from the block list. **This should be unblocked.** - source: https://umbrella.cisco.com/blog/2015/06/02/samsungs-chatty-smarttvs/ 

connecttv.pelmorex.com

^ This is likely a Weatherapp tracking URL, not necessary for the functionality of the app or TV. This URL can be blocked without causing issues to functionality. **This should be blocked.**

**Comment by Perflyst** [comment]
Your source is dead, archived: https://web.archive.org/web/20170814113950/https://umbrella.cisco.com/blog/2015/06/02/samsungs-chatty-smarttvs/

**Comment by redanish** [comment]
Hi @Perflyst , you're right but the comments still stand - are these changes being incorporated into the list?

thanks again!

**Comment by redanish** [comment]
whoops just checked that they have been thanks! 👍
