### ISSUE TITLE
Missing sony domains

### ISSUE THREAD

**Issue by bog500** [Perflyst/PiHoleBlocklist#55]
this might be missing a few, I'm seeing requests to the following domain on my network coming from Sony TVs (not sure what they are actually for, some might be needed for certain services or updates):

ssm2.internet.sony.tv
ssm3.internet.sony.tv
reg.biv.sony.tv
service.biv.sony.tv
update.biv.sony.tv

**Comment by Perflyst** [comment]
> ssm2.internet.sony.tv, ssm3.internet.sony.tv

looks like they are for app / app store

>  reg.biv.sony.tv

sony account registration?

> service.biv.sony.tv, update.biv.sony.tv

probably for updates

**Comment by bog500** [comment]
you are right, without all the following domains the TV can't open the Netflix app, so they must remain whitelisted

ssm3.internet.sony.tv
service.biv.sony.tv
update.biv.sony.tv
reg.biv.sony.tv

as for ssm2.internet.sony.tv it can remain blocked (at least for my TV)
