### ISSUE TITLE
link to unblock for updating Samsung TV

### ISSUE THREAD

**Issue by FireFeet** [Perflyst/PiHoleBlocklist#60]
Hi!

Thank you for the great list! 

I want to share with you that I had to unblock `otn.samsungcloudcdn.com` to update my Samsung UE49KS7000 Smart TV.

I will share any other finding.

Keep up the good work!

**Comment by s1mwest** [comment]
Yes, thank you for this list!  Really is great and helpful work.

I also had to unblock otn.samsungcloudcdn.com for updates for my Q9FN QLED (QE55Q9FNA)
