### ISSUE TITLE
Do you think "Red Button" infos are annyoing and should be blocked?

### ISSUE THREAD

**Issue by Perflyst** [Perflyst/PiHoleBlocklist#61]
Do you all think that we should block Red Button information? I personally think it is annoying to get these kind of popups while watching TV.

We already block some "HBBTV" domains, but some are whitelisted like "hbbtv.redbutton.de" because they block "ZDF / ProSieben apps". What are these kind of apps?

**Comment by s1mwest** [comment]
If I understand this correctly, you're referring to (or including) the pop-up notifications when watching BBC1 in UK that notify you to catch up on iPlayer.
Yes, annoys me too! I've just blocked tap.api.bbc.co.uk which seems to stop the red/green button notifications that show on my Samsung Q9FN.  I'l update here if it causes me any issues or if I see further pop-ups

**Comment by realErtugrul** [comment]
I would create an extra file for this. Because many People use the Red Button frequently.

**Comment by s1mwest** [comment]
Perhaps keep it in the main file but rem'd out by default and notated so it can be enabled by users like some of the other addresses.
