### ISSUE TITLE
clients1.google.com false positiv

### ISSUE THREAD

**Issue by beerisgood** [Perflyst/PiHoleBlocklist#7]
in android-tracking.txt you block clients1.google.com but as i see, some apps or even Android itself need this (sometimes?).

**Comment by Perflyst** [comment]
No, see #5 for more information.

**Comment by beerisgood** [comment]
Ah good to know. Thanks

**Comment by lightswitch05** [comment]
I agree that this is a false positive and should be removed from the list.

> as search suggestions are personalized by tracking

I believe there is a difference between the domains that **use tracking data** and **domains that track**. Clearly, you are saying that search suggestions are personalized and therefore should be blocked. However, all Google searches are also personalized, are you going to block google.com? In fact, me being logged into Github at this moment means that github is personalizing to me - should github.com be blocked as well? I think there is a distinction between tracking and personalizing.

**Comment by lightswitch05** [comment]
For another references, people commonly whitelist these because of the broken functionality:

https://github.com/anudeepND/whitelist/blob/52353a7757334cd1201d138ee7b6bdc415b78c36/domains/whitelist.txt#L34-L39

**Comment by lightswitch05** [comment]
Also https://github.com/anudeepND/whitelist/issues/24
