### ISSUE TITLE
hdhomerun.com domains

### ISSUE THREAD

**Issue by bpennypacker** [Perflyst/PiHoleBlocklist#78]
These domains should likely be removed. They prevent the legitimate use of HDHomerun devices, including things like firmware updates, etc. Ads, etc. certainly are not served via these domains:

   tuner-api.hdhomerun.com 
   location-api.hdhomerun.com 

A bit more information can be found here: https://forum.silicondust.com/forum/viewtopic.php?p=364251#p364251

**Comment by NedScott** [comment]
Hi, I'm Ned Scott from Silicondust. Just to chime in, we don't do ads, and we have never sold customer data. These URLs are used to help configure the HDHomeRun app so that the correct local TV guide is loaded, and will actually prevent the HDHomeRun app from being able to function if blocked.

**Comment by Perflyst** [comment]
Thanks for reaching out, both domains are now removed.

> we don't do ads

That is great to hear!

> and we have never sold customer data.

Blocking unknown domains that could be used to track usage etc is still better than trusting a company not to sell user data ;)
The blocklists are not only for ads.
