### ISSUE TITLE
How I got my Samsung TV to accept commands from Google Home again

### ISSUE THREAD

**Issue by dbensmith** [Perflyst/PiHoleBlocklist#79]
My Samsung UN55NU8000 TV couldn't be reached by Google Home until I added this filter to my allowlist in AGH:

`@@||osb.samsungqbe.com^`

After that, Google Home could turn my TV on/off and switch inputs again.

I haven't submitted a PR before so I thought I would mention it here before trying anything.

Hope this helps!

**Comment by dbensmith** [comment]
As it turns out, my issue wasn't related to DNS blocklists, although I learned that `osb.samsungqbe.com` is required for Samsung Account login on my smart TV.

Thanks for your work on these blocklists @Perflyst!

**Comment by Perflyst** [comment]
Maybe it is still valid to remove this domain then. Samsung Account login sounds like a legit use case
