### ISSUE TITLE
Consider using a GitHub Pages site to host lists

### ISSUE THREAD

**Issue by Trainax** [Perflyst/PiHoleBlocklist#81]
The use of raw.githubusercontent URLs is considered bad form for Pi-hole since it will re-download the list every time it updates. You should consider setting up a GitHub Pages site (using the root directory of this repository as source) and then use those URLs to point to the lists. This will include the last-modified data in the header preventing Pi-hole from pulling the list if nothing has changed. The addresses for the lists would then be similar to:

https://perflyst.github.io/PiHoleBlocklist/SmartTV.txt

These are smaller URLs as well which are easier to read on the web interface (while also reducing wear on an SD card for Pi-hole hosted on actual Raspberry Pi hardware due to not downloading unless there are changes). This would not break anyone that is currently using the raw.githubusercontent URLs, but would provide a better source for anyone that wants to change them over as well as new users.

More information:
- https://discourse.pi-hole.net/t/i-concatenated-every-blocklist-i-could-find/5184/2
- https://docs.github.com/en/github/working-with-github-pages/creating-a-github-pages-site

Thank you

### How to enable Pages for this project

Go to settings -> scroll down to the GitHub Pages section -> select *main* as branch and */(root)* as folder in source -> click save

**Comment by Trainax** [comment]
Hello @Perflyst, sorry to bother you. Any updates on this?

Enabling GitHub Pages in this repository is an operation which takes ~10 seconds, costs nothing in terms of money and could make using the lists better.

If you enable GitHub Pages I'm willing to make a PR to this project to add a table in the README file with all the links to the lists if you want.

Thank you

**Comment by Perflyst** [comment]
Thanks for the reminder. GH pages is enabled now. Feel free to submit a PR
