### ISSUE TITLE
Fire TV: amazonadsi-a.akamaihd.net needed for app updates

### ISSUE THREAD

**Issue by tobiwashere** [Perflyst/PiHoleBlocklist#84]
Hi,

I needed to whitelist `amazonadsi-a.akamaihd.net` to be able to install app updates on my fire tv stick.
Maybe it needs [this](https://amazonadsi-a.akamaihd.net/public/) list for the app updates, but I'm not completely sure about this...

Tobi

**Comment by pedrolamas** [comment]
I can confirm this issue as I have experienced it myself with two different Fire tablets: an Amazon Fire HD 8 and an Amazon Fire HD 10 (both Kids versions used by my kids...)

With that rule on, they are unable to install some apps from their Kids Freetime subscription... once I whitelisted the url, everything started to work again!

**Comment by Perflyst** [comment]
Thank you, removed with d6981b0a9a044acf65f7803e729a086fe6a395b3
