### ISSUE TITLE
how to use regex.list

### ISSUE THREAD

**Issue by masterkain** [Perflyst/PiHoleBlocklist#89]
https://github.com/Perflyst/PiHoleBlocklist/blob/master/regex.list

I would like to use this one `^api\..*\.hismarttv\.com$`

is it possible to use the raw url and add it to the pihole adlists? when I try it says 0 domains found.

```
  [i] Target: https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/regex.list
  [✓] Status: Retrieval successful
  [i] Received 0 domains

```

**Comment by Perflyst** [comment]
Back in the times there was a regex.list, now Pihole stores everything in sqlite... It should still work to add it manually
![Screenshot_20210208_072646](https://user-images.githubusercontent.com/26308977/107183374-00faec00-69df-11eb-890d-a69fb8b78e66.png)
