### ISSUE TITLE
Sony Smart TV updates getting blocked

### ISSUE THREAD

**Issue by Salvora** [Perflyst/PiHoleBlocklist#90]
Below four domains are getting blocked resulting in TV not getting any updates.
I am not sure which ones are for TV software updates.

ssm1.internet.sony.tv
ssm2.internet.sony.tv
ssm3.internet.sony.tv
update.biv.sony.tv

**Comment by Perflyst** [comment]
Can you whitelist one after another until you find the domain which blocks updates?

**Comment by Salvora** [comment]
update.biv.sony.tv
seems to be the update server

**Comment by Perflyst** [comment]
Thank you, removed with 724794c6236686019d6950397c262fa7bbf11b3d
