### ISSUE TITLE
Netflix: nrdp.prod.ftl.netflix.com

### ISSUE THREAD

**Issue by whoot** [Perflyst/PiHoleBlocklist#91]
Please add `nrdp.prod.ftl.netflix.com` to the SmartTV.txt
My SmartTV is sending a lot of requests to this domain. Manually adding it to the Blacklist did not result in any issues so I guess it is used for tracking or some kind of stuff?

**Comment by Perflyst** [comment]
Thanks, added with b1ea84e8a64a2ba1ac378d2423bc21e4df940a6b
