### ISSUE TITLE
LG domains

### ISSUE THREAD

**Issue by janmyler** [Perflyst/PiHoleBlocklist#95]
Hi there, I have my LG TV registered on the Japanese regional market and some of the domains have `jp` instead of `us`.

Example:
```
jp.rdx2.lgtvsdp.com
JP.lgtvsdp.com
JP.info.lgsmartad.com
```

I assume this is true for other regions as well. Is it ok to add the `jp.*` domains to this list?

**Comment by JacobMillward** [comment]
Seem reasonable to me, maybe try a PR.
